global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Node Exporter untuk monitoring host metrics
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  # E-Commerce Dashboard
  - job_name: 'ecommerce-app'
    static_configs:
      - targets: ['ecommerce-app:8001']

  # Weather Monitoring
  - job_name: 'weather-app'
    static_configs:
      - targets: ['weather-app:8002']

  # Social Media Analytics
  - job_name: 'social-app'
    static_configs:
      - targets: ['social-app:8003']
